### PR TITLE
Improve Secrecy

### PR DESCRIPTION
**Pull request by ghost**
Most of the time, you are using the bot on public servers. This causes
a problem since the mcspambot usually screams out what it is doing to
the whole server. This patch fix makes the bot reply to the owner that
is messaging it, improving the secrecy but not causing much harm

Most server has the /r command so it should be no problem

### CODE REVIEW

**Comment by DarkStorm652** [comment]
A much better and object-oriented solution to this would be to simply write a modified version of
https://github.com/DarkStorm652/DarkBot/blob/master/src/minecraft/java/org/darkstorm/darkbot/mcspambot/ChatBackend.java
that prefixes all messages with "/r ". This pull request won't work because IRCBackend will send all messages prefixed with /r.

**Comment by ghost** [comment]
I still don't know how to get the IRC to work :P Will see what I can do for the chatbackend. Wonderful bot btw :)

**Comment by ghost** [comment]
This bot is so poorly documented that not even professional skids know how to use it. Took me awhile looking at the raw code to find out how to use the bot.

**Comment by TrevorLaneRay** [comment]
I know, but hey... at least it gives you a challenge, and prevents mass usage by general public.
(Though yeah, I could use some documentation meself. :)

**Comment by ghost** [comment]
LOL, I don't need much help since I scanned through every single code to find out how to control the bot :P Add me on skype, answer a few anti-skid questions and I will be happy to teach you :).

@DarkStorm652 The amount of documentation is too damn low, but its good. Completely anti-skidder based :+1:

**Comment by DarkStorm652** [comment]
Hehehe, I don't ever Javadoc or comment because it wastes immense amounts of time and because descriptive naming and clear structure are quite enough for an experienced programmer to follow.

**Comment by ghost** [comment]
True that, still, I really admire your method of skidproofing :)

**Comment by DarkStorm652** [comment]
Actually not an intentional method, I just do it because the code speaks for itself and comments are superfluous.

**Comment by ghost** [comment]
Maybe, it seems that your bot has stirred up a lot of attention at MPGH where a lot of skids reside. Fear not, I did not bother to teach them.

**Pull request closed without merging**
